Makefile.am
I'm assuming you're using guix or something like it -- this just uses $(GUILE) in the makefile so that way I can run with the guile-git package from archlinux. Thanks for making the env script in this project, makes everything else super easy :)
=> Makefile.am: Use $(GUILE) for running tests

fibers.texi
The procedure `signal-condition!` wasn't documented, and I remember having to read the source to find out what this procedure was named.
=> Document signal-condition!

fibers.scm, fibers.texi
As #33 points out, scheduler is a optional argument to spawn-fiber,
not a keyword argument.
=> Fix #33: Scheduler is an optional argument

fibers.texi
* fibers.texi (Channels)[get-message]: Replace 'receiver' by 'sender'.
=> fibers.texi: Correct wording.

fibers/scheduler.scm
As civodul pointed out in Issue #19, the EPOLLHUP events are
improperly handled which leads to a epoll_wait/epoll_ctl loop.
From epoll_ctl(2):
EPOLLERR
Error condition happened on the associated file descriptor.  This
event is also reported for the write end of a pipe when the read
end has been closed.
epoll_wait(2) will always report for this event; it is not
necessary to set it in events when calling epoll_ctl().
EPOLLHUP
Hang up happened on the associated file descriptor.
epoll_wait(2) will always wait for this event; it is not necessary
to set it in events when calling epoll_ctl().
Note that when reading from a channel such as a pipe or a stream
socket, this event merely indicates that the peer closed its end
of the channel.  Subsequent reads from the channel will return
0 (end of …
=> Fix #19 by handling EPOLLHUP like EPOLLERR

fibers/epoll.scm, tests/conditions.scm
Fixes: https://github.com/wingo/fibers/issues/61
=> Fix ‘epoll instance is dead #61’

Makefile.am, fibers/web/server.scm, tests/concurrent-web-server.scm
Previously, any response would have to be entirely in memory prior to
the first byte being sent to the client. This is fine for small
response bodies like web pages, but can be undesirable when the
response body is large or takes time to compute.
=> Support streaming responses in the responses in the fibers web server

Makefile.am, fibers.texi, fibers/io-wakeup.scm, tests/io-wakeup.scm
I have used a previous version of this patch in https://notabug.org/maximed/scheme-gnunet/ for a while to implement message queues.  It can be used like:
```scheme
;; Untested, but I have been doing something similar for a while
;; in <https://notabug.org/maximed/scheme-gnunet/src/master/gnu/gnunet/mq-impl/stream.scm>.
(let ((old-waiter (current-read-waiter)))
(let/ec escape
(parameterize ((current-read-waiter
(lambda (port)
(if (eq? port my-port)
(perform-operation
(choice-operation (wait-until-port-readable-operation my-port))
(wrap-operation (wait-operation condition)
(lambda () (escape 'interrupted))))
(old-waiter port)))))
(read-line my-port)))
```
=> Implement operations for waiting for readability / writability

.gitignore, Makefile.am, build-aux/guile.am, configure.ac, env.in, fibers/epoll.scm, fibers/events-impl.scm, fibers/libevent.scm, fibers/posix-clocks-darwin.scm, fibers/posix-clocks.scm
This avoids a potential cross-compilation issue, see the rationale in fibers/events-impl.scm
=> Eliminate FIBERS_CROSS_COMPILING

fibers.scm
this should fix https://github.com/wingo/fibers/issues/79
it's based on @civodul's recommended way of resolving it. (thanks!)
the `guile-fibers` Guix package builds fine with this commit, including the tests.
note: i still see one warning when i'm running a `guix system vm` with a custom `shepherd` as PID 1, that uses a custom `guile-fibers` with this commit. i hope that it's due to my failure to fully understand the Guix machinery, and not that the deprecation warning still gets triggered even with this commit included.
@civodul i would appreciate if you could test this PR in the above environment while you're working on shepherd, or just take a look and point out any issues that you spot.
=> fix: avoid deprecation warnings for bit-vector functions

Makefile.am, fibers/scheduler.scm, fibers/timer-wheel.scm, tests/basic.scm, tests/timer-wheel.scm
This PR adds a timer wheel, like https://www.snellman.net/blog/archive/2016-07-27-ratas-hierarchical-timer-wheel/.  I ported it from https://github.com/snabbco/snabb/blob/master/src/lib/fibers/timer.lua, which I also wrote.  It seems to increase the number of threads that can `(sleep 1)` concurrently by about a factor of 15 or so.  WDYT @aconchillo ?
=> Replace PSQ timer queue with a timer wheel

extensions/libevent.c
Fixes #86.
* extensions/libevent.c (run_event_loop): Check whether TIME_UNITS_PER_MICROSEC is zero before dividing.
=> libevent: Avoid division by zero on 32-bit platforms.

extensions/libevent.c
This reverts commit 47fa38f580ccd0a6109ace444657eabc15200a22: there's no need to explicitly free this via a finalizer since it lives in GC-managed heap with references in GC-scanned heap.
=> Revert "libevent: gc free wait_data"

NEWS, fibers.texi, fibers/io-wakeup.scm, tests/io-wakeup.scm
E.g., this makes it easy to define an 'accept-operation' for accepting sockets.
=> Define constructors for I/O operations.

fibers.texi
I see no reason for not rendering the index that already is there.
The concept index is currently also empty, but I enabled it to in case something gets added to it later.
=> texi: un-comment indices.

NEWS, fibers.texi, fibers/io-wakeup.scm, fibers/scheduler.scm, tests/basic.scm, tests/io-wakeup.scm
The default record printer in Guile seems to produce a large (maybe infinite) output for schedulers, so this simple record printer prevents that.
=> scheduler: Set a simple custom record printer.

fibers/io-wakeup.scm
Replace readable? by writable?.
Should be trivial, but let's check CI.
=> Fix wait-until-port-writable-operation.

extensions/libevent.c
Until now, sleeping for 10s or more wouldn’t work on platforms where internal-time-units-per-second = 1e9, such as x86_64-linux-gnu.
On platforms where internal-time-units-per-second = 1e3, such as i586-pc-gnu, ‘tv’ would always be zero, leading to code that keeps spinning.
* extensions/libevent.c (microsec_per_time_units): New variable.
(run_event_loop): Fix computation of ‘tv_sec’ and ‘tv_usec’.
(init_fibers_libevt): Initialize ‘microsec_per_time_units’.
=> libevent: Fix computation of the timeout value.

Makefile.am, fibers/operations.scm, fibers/scheduler.scm, fibers/timer-wheel.scm, fibers/timers.scm, tests/cancel-timer.scm
This patch series fixes #109 by supporting a "cancel" function for base operations and using it to remove timer wheel entries when a timer "loses" in a choice operation.
I'd like feedback in particular on the last commit: can someone confirm `set!` good enough, or should we use an atomic box instead?
I ran the test suite of the Shepherd and that of Cuirass against this branch: the former has good coverage though it uses a single POSIX thread, the latter has not-so-good coverage but uses multiple POSIX threads.  Both passed.
Thoughts?
=> Support cancellation of timer operations

Makefile.am, build-aux/guile.am, guix.scm, tests/basic.scm, tests/speedup.scm
This change ensures `make check` runs in a timely fashion, particularly in Guix build environments.
Why Guix? Because the default `$HOME` in build environments in not writable, meaning that tests were not auto-compiled, and thus `loop-to-1e4` and similar would take *much* longer (especially on low-end AArch64 or RISC-V machines where it would typically time out after an hour).
=> Speeding up 'make check'
